from os import path

WIDTH, HEIGHT = 800, 480

SCROLL_SPEED = 3

PLANE_ANIMATION_DELAY = 0.1
PLANE_BOOST_VEL = -13
PLANE_GRAVITY = 1
PLANE_GRAVITY_LIMIT = 5
PLANE_UP_ANGLE_LIMIT = 40
PLANE_DOWN_ANGLE_LIMIT = 90
PLANE_UP_ANGLE_VEL = 4
PLANE_DOWN_ANGLE_VEL = 2
PLANE_KEEP_ANGLE_TIME = .28

THEMES = [
    "grass",
    "snow",
    "ice"
]

ROCK_X_DIST = 200

